repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff
        args: [--fix]
        exclude: migrations
      - id: ruff-format
        exclude: migrations
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-json
        exclude: docs/dev|.devcontainer/devcontainer.json|.vscode/launch.json
      - id: check-yaml
        exclude: (deploy/host_vars|deploy/stack|deploy)
      - id: check-xml
      - id: debug-statements
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key