# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-24 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0003_auto_20170924_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-date',)},
        ),
    ]
