# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-24 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0004_auto_20170924_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='month',
            field=models.ForeignKey(default=1, help_text='The month that this Transaction occurred in.', on_delete=django.db.models.deletion.PROTECT, to='occurrence.Month'),
            preserve_default=False,
        ),
    ]
