# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-30 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0006_auto_20170924_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='slug',
            field=models.SlugField(default='september-2017', unique=True),
            preserve_default=False,
        ),
    ]
