# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-01 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0008_category_type_cat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='ExpenseTransaction',
        ),
    ]
