# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-01 00:34
from __future__ import unicode_literals

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0009_auto_20170930_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('receipt', models.ImageField(blank=True, upload_to='transaction_receipts/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='occurrence.Category')),
                ('month', models.ForeignKey(blank=True, help_text='The month that this Transaction occurred in.', on_delete=django.db.models.deletion.PROTECT, to='occurrence.Month')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
