# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-14 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0011_category_running_total_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='running_total_category',
        ),
        migrations.AddField(
            model_name='category',
            name='total_type',
            field=models.CharField(choices=[('regular', 'Regular total'), ('running', 'Running total')], default='regular', help_text='When finding totals for this Category, how should the totals be displayed? Some Categories may need to be excluded from the totals, and be displayed on their own page.', max_length=20),
        ),
    ]
