# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-22 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0013_category_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('order', 'name'), 'verbose_name_plural': 'Categories'},
        ),
    ]
