# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0015_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='occurrence.Month')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='monthlystatistic',
            name='statistic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='occurrence.Statistic'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlystatistic',
            unique_together=set([('statistic', 'month')]),
        ),
    ]
