# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 00:46
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0016_auto_20180721_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedMonthlyCategoryTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='occurrence.Category')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='occurrence.Month')),
            ],
            options={
                'ordering': ['category__order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='expectedmonthlycategorytotal',
            unique_together=set([('category', 'month')]),
        ),
    ]
