# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0016_auto_20180721_0919'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlystatistic',
            unique_together=set([('statistic', 'month')]),
        ),
    ]
