# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0017_auto_20180721_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
