# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0018_statistic_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistic',
            options={'ordering': ['order']},
        ),
    ]
