# Generated by Django 4.2 on 2025-07-14 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data_tools", "0001_initial"),
        ("occurrence", "0019_auto_20200625_2134"),
    ]

    operations = [
        migrations.AddField(
            model_name="earningtransaction",
            name="csv_import",
            field=models.ForeignKey(
                blank=True,
                help_text="The CSV import this transaction was created from.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="data_tools.csvimport",
            ),
        ),
        migrations.AddField(
            model_name="expensetransaction",
            name="csv_import",
            field=models.ForeignKey(
                blank=True,
                help_text="The CSV import this transaction was created from.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="data_tools.csvimport",
            ),
        ),
    ]
