# Generated by Django 4.2 on 2025-07-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("occurrence", "0020_earningtransaction_csv_import_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="earningtransaction",
            name="pending",
            field=models.BooleanField(default=False),
        ),
    ]
