# Generated by Django 4.2 on 2026-03-18 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data_tools", "0004_categorymapping"),
        ("occurrence", "0021_earningtransaction_pending"),
    ]

    operations = [
        migrations.AlterField(
            model_name="earningtransaction",
            name="csv_import",
            field=models.ForeignKey(
                blank=True,
                help_text="The CSV import this transaction was created from.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_tools.csvimport",
            ),
        ),
        migrations.AlterField(
            model_name="expensetransaction",
            name="csv_import",
            field=models.ForeignKey(
                blank=True,
                help_text="The CSV import this transaction was created from.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_tools.csvimport",
            ),
        ),
    ]
