# Generated by Django 6.0.4 on 2026-05-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0022_alter_earningtransaction_csv_import_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expectedmonthlycategorytotal',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='monthlystatistic',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='expectedmonthlycategorytotal',
            constraint=models.UniqueConstraint(fields=('category', 'month'), name='unique_expectedmonthlycategorytotal_category_month'),
        ),
        migrations.AddConstraint(
            model_name='monthlystatistic',
            constraint=models.UniqueConstraint(fields=('statistic', 'month'), name='unique_monthlystatistic_statistic_month'),
        ),
    ]
