# Generated by Django 4.2 on 2025-09-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_tools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvimport",
            name="rows_created",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of transactions created from this import"
            ),
        ),
        migrations.AddField(
            model_name="csvimport",
            name="rows_skipped",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of rows skipped during this import"
            ),
        ),
    ]
