# Generated by Django 4.2 on 2025-09-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_tools", "0002_csvimport_rows_created_csvimport_rows_skipped"),
    ]

    operations = [
        migrations.CreateModel(
            name="TitleMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_title",
                    models.CharField(
                        help_text="The title variation that appears in CSV files",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "canonical_title",
                    models.CharField(
                        help_text="The canonical title to use for all matching variations",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["canonical_title", "source_title"],
            },
        ),
    ]
