# Generated by Django 4.2 on 2026-03-03 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0021_earningtransaction_pending'),
        ('data_tools', '0003_titlemapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_title', models.CharField(help_text='The title of a transaction', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, help_text='The category to assign to transactions with this source title', null=True, on_delete=django.db.models.deletion.SET_NULL, to='occurrence.category')),
            ],
            options={
                'ordering': ['source_title'],
            },
        ),
    ]
