name: Lint and Test code

on:
  pull_request:
  schedule:
    # run once a week at 1:30 AM on Monday mornings
    - cron: '30 1 * * 1'

jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      DJANGO_SETTINGS_MODULE: skameika.settings.dev
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: skameika_ci
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements/**.txt'
      - name: Cache pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-precommit-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements/base.txt requirements/dev.txt
      - uses: pre-commit/action@v3.0.0
      - name: Run Tests
        run: make test
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/skameika_ci
